export interface Company {
 id: number,
    company: string,
    document: string,
    country: string,
    city: string,
    address: string,
    phone: string,
    email: string,
    contact: string,
    contact_phone: string,
    contact_email: string,
    image1: string,
    tokenWeb: string,
    urlAPI: string,
    lat: string,
    lon: string,
    active: boolean,
    bank1: string,
    bank2: string,
    bank3: string,
}
