export interface WebContent {
    id: number;
    menu: string;
    type: string;
    metadescription: string;
    metakeywords: string;
    content_id: number;
    title: string;
    subtitle: string;
    text1: string;
    text2: string;
    text3: string;
    text4: string;
    image1: string;
    image2: string;
    image3: string;
    image4: string;
    image_text1: string,
    image_text2: string,
    image_text3: string,
    image_text4: string,
    image_link1: string,
    image_link2: string,
    image_link3: string,
    image_link4: string,
    video: string;
    position: number;
    link: string;
}